name: Deploy Airflow DAGs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install apache-airflow

      - name: Deploy DAGs
        run: |
           rsync -a --include="*/" --include="*.py" --exclude="*" airflow/dags/ ~/airflow-docker/dags/
           airflow db init
           airflow webserver -p 8080 -D
           airflow scheduler -D

