name: Deploy Airflow DAGs
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install apache-airflow

#      - name: Create DAGs directory
#        run: |
#          mkdir -p ~/airflow-docker/dags/

#      - name: Copy DAGs
#        run: |
#          rsync -a --include="*.py" --exclude="*" . ~/airflow-docker/dags/
#          cd ~/airflow-docker
#          airflow db init
#          airflow webserver -p 8080 -D
#          airflow scheduler -D
      - name: Copy DAGs
        run: |
          rsync -a --include="*.py" --exclude="*" . ~/airflow/dags/
          cd ~/airflow
          airflow db init
          airflow webserver -p 8080 -D
          airflow scheduler -D
